# Generated by Django 6.0.7 on 2026-09-12 08:40

import api.managers
import api.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_booked', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Specialties',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('national_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='کد ملی')),
                ('avatar', models.ImageField(blank=True, default='user_avatars/avatar.svg', null=True, upload_to=api.models.user_avatar_upload_path, verbose_name='عکس پروفایل')),
                ('ban_reason', models.TextField(blank=True, help_text='در صورتی که نقش کاربر «مسدود» باشد، این فیلد الزامی است.', verbose_name='دلیل مسدودسازی')),
                ('is_phone_verified', models.BooleanField(default=False, verbose_name='تلفن تایید شده')),
                ('is_staff', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('super_admin', 'مدیر کل'), ('admin', 'ادمین'), ('moderator', 'پشتیبان'), ('user', 'کاربر'), ('counselor', 'خدمت دهنده'), ('guest', 'مهمان'), ('banned', 'مسدود')], default='user', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', api.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='api.availabilityslot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Counselor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='شماره پروانه')),
                ('nezam_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='شماره نظام')),
                ('degree', models.CharField(blank=True, max_length=100, null=True, verbose_name='مدرک تحصیلی')),
                ('bio', models.TextField(blank=True, verbose_name='درباره من')),
                ('session_price', models.PositiveIntegerField(default=0, verbose_name='هزینه هر جلسه (تومان)')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تایید شده توسط ادمین')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'counselor'}, on_delete=django.db.models.deletion.CASCADE, related_name='counselor_profile', to=settings.AUTH_USER_MODEL)),
                ('specialties', models.ManyToManyField(blank=True, related_name='counselors', to='api.specialty')),
            ],
        ),
        migrations.AddField(
            model_name='availabilityslot',
            name='counselor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='api.counselor'),
        ),
        migrations.CreateModel(
            name='CounselorCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=api.models.counselor_certificate_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='api.counselor')),
            ],
        ),
        migrations.CreateModel(
            name='CounselorNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counselor_notes', to=settings.AUTH_USER_MODEL)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_notes', to='api.counselor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('phone', 'تلفن')], max_length=10)),
                ('purpose', models.CharField(choices=[('login', 'ورود'), ('verify', 'تایید حساب'), ('password_reset', 'بازیابی رمز عبور')], default='login', max_length=20)),
                ('destination', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=5)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False, verbose_name='تایید شده برای نمایش عمومی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='api.booking')),
            ],
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('in_progress', 'در حال بررسی'), ('resolved', 'پاسخ داده شد')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_replies', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.supportticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='availabilityslot',
            constraint=models.UniqueConstraint(fields=('counselor', 'date', 'start_time'), name='unique_counselor_slot'),
        ),
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['destination', 'channel', 'is_used'], name='api_otpcode_destina_044e5a_idx'),
        ),
    ]
