# Generated by Django 6.0.7 on 2026-08-15 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'مدیر کل'), ('admin', 'ادمین'), ('moderator', 'پشتیبان'), ('user', 'کاربر'), ('counselor', 'خدمت دهنده'), ('guest', 'مهمان')], default='user', max_length=20),
        ),
        migrations.CreateModel(
            name='Counselor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=50, unique=True, verbose_name='شماره پروانه')),
                ('nezam_number', models.CharField(max_length=50, unique=True, verbose_name='شماره نظام')),
                ('degree', models.CharField(max_length=100, verbose_name='مدرک تحصیلی')),
                ('bio', models.TextField(blank=True, verbose_name='درباره من')),
                ('session_price', models.PositiveIntegerField(default=0, verbose_name='هزینه هر جلسه (تومان)')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تایید شده توسط ادمین')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'counselor'}, on_delete=django.db.models.deletion.CASCADE, related_name='counselor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CounselorCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='counselor_certificates/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='api.counselor')),
            ],
        ),
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='api.counselor')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'constraints': [models.UniqueConstraint(fields=('counselor', 'date', 'start_time'), name='unique_counselor_slot')],
            },
        ),
    ]
