# Generated by Django 6.0.7 on 2026-08-15 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_national_id_alter_user_role_counselor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('phone', 'تلفن'), ('email', 'ایمیل')], max_length=10)),
                ('purpose', models.CharField(choices=[('login', 'ورود'), ('verify', 'تایید حساب'), ('password_reset', 'بازیابی رمز عبور')], default='login', max_length=20)),
                ('destination', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=5)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='availabilityslot',
            name='unique_counselor_slot',
        ),
        migrations.RemoveField(
            model_name='counselor',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, verbose_name='ایمیل تایید شده'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_phone_verified',
            field=models.BooleanField(default=False, verbose_name='تلفن تایید شده'),
        ),
        migrations.AddField(
            model_name='otpcode',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='availabilityslot',
            name='counselor',
        ),
        migrations.DeleteModel(
            name='CounselorCertificate',
        ),
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['destination', 'channel', 'is_used'], name='api_otpcode_destina_044e5a_idx'),
        ),
        migrations.DeleteModel(
            name='AvailabilitySlot',
        ),
        migrations.DeleteModel(
            name='Counselor',
        ),
    ]
