# Generated by Django 6.0.7 on 2026-09-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_birth_date_user_gender_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselor',
            name='address',
            field=models.TextField(blank=True, verbose_name='آدرس کامل'),
        ),
        migrations.AddField(
            model_name='counselor',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='counselor',
            name='session_format',
            field=models.CharField(choices=[('online', 'آنلاین'), ('in_person', 'حضوری'), ('both', 'آنلاین و حضوری')], default='online', max_length=10, verbose_name='نوع جلسه'),
        ),
        migrations.AlterField(
            model_name='counselor',
            name='degree',
            field=models.CharField(default='', max_length=100, verbose_name='مدرک تحصیلی'),
        ),
    ]
