# Generated by Django 6.0.7 on 2026-09-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_counselor_address_counselor_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselor',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=150, unique=True, verbose_name='لینک اختصاصی'),
        ),
    ]
