# Generated by Django 6.0.7 on 2026-09-14 10:03

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_counselor_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselor',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0, verbose_name='سابقه کار (سال)'),
        ),
        migrations.CreateModel(
            name='CounselorGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=api.models.counselor_gallery_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='api.counselor')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
