# Generated by Django 6.0.7 on 2026-09-15 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_counselor_years_of_experience_counselorgalleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityslot',
            name='source',
            field=models.CharField(choices=[('manual', 'دستی'), ('generated', 'خودکار')], default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('paid', 'پرداخت شده'), ('cancelled_refunded', 'لغو شده - عودت وجه'), ('cancelled_no_refund', 'لغو شده - بدون عودت')], default='paid', max_length=20),
        ),
        migrations.AlterField(
            model_name='counselor',
            name='degree',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مدرک تحصیلی'),
        ),
        migrations.CreateModel(
            name='CounselorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_duration_minutes', models.PositiveIntegerField(default=45)),
                ('gap_minutes', models.PositiveIntegerField(default=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counselor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='api.counselor')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('vacation', 'مرخصی'), ('holiday', 'تعطیل'), ('blocked', 'مسدود'), ('custom_hours', 'ساعت خاص')], max_length=20)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_exceptions', to='api.counselor')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleWorkingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'شنبه'), (1, 'یکشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنجشنبه'), (6, 'جمعه')])),
                ('is_enabled', models.BooleanField(default=False)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_days', to='api.counselorschedule')),
            ],
            options={
                'ordering': ['weekday'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('working_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='api.scheduleworkingday')),
            ],
        ),
        migrations.AddConstraint(
            model_name='scheduleworkingday',
            constraint=models.UniqueConstraint(fields=('schedule', 'weekday'), name='unique_schedule_weekday'),
        ),
    ]
