# Generated by Django 6.0.7 on 2026-09-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_booking_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price_at_booking',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
