# Generated by Django 6.0.7 on 2026-09-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_paymenttransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار بررسی'), ('in_progress', 'در حال بررسی'), ('resolved', 'پاسخ داده شد'), ('closed', 'بسته شده')], default='pending', max_length=20),
        ),
    ]
