# Generated by Django 6.0.7 on 2026-09-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Specialties',
            },
        ),
        migrations.AddField(
            model_name='counselor',
            name='specialties',
            field=models.ManyToManyField(blank=True, related_name='counselors', to='api.specialty'),
        ),
    ]
