# Generated by Django 6.0.7 on 2026-09-16 21:05

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_heroslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=api.models.plan_image_upload_path)),
                ('title', models.CharField(max_length=100)),
                ('features', models.TextField(help_text='هر ویژگی در یک خط جداگانه')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت (تومان)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
