# Generated by Django 6.0.7 on 2026-09-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_supportticket_ticketreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='تایید شده برای نمایش عمومی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'مدیر کل'), ('admin', 'ادمین'), ('moderator', 'پشتیبان'), ('user', 'کاربر'), ('counselor', 'خدمت دهنده'), ('guest', 'مهمان'), ('banned', 'بلاک شده')], default='user', max_length=20),
        ),
    ]
