# Generated by Django 6.0.7 on 2026-09-17 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='purpose',
            field=models.CharField(choices=[('booking', 'رزرو نوبت'), ('subscription', 'خرید اشتراک')], default='booking', max_length=20),
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_at_purchase', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('active', 'فعال'), ('cancelled', 'لغو شده')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='api.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='api.usersubscription'),
        ),
    ]
