# Generated by Django 6.0.7 on 2026-09-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_review_is_approved_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ban_reason',
            field=models.TextField(blank=True, help_text='در صورتی که نقش کاربر «مسدود» باشد، این فیلد الزامی است.', verbose_name='دلیل مسدودسازی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'مدیر کل'), ('admin', 'ادمین'), ('moderator', 'پشتیبان'), ('user', 'کاربر'), ('counselor', 'خدمت دهنده'), ('guest', 'مهمان')], default='user', max_length=20),
        ),
    ]
