# Generated by Django 6.0.7 on 2026-09-19 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_coupon_plansale'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='api.coupon'),
        ),
    ]
