# Generated by Django 6.0.7 on 2026-09-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_user_ban_reason_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'مدیر کل'), ('admin', 'ادمین'), ('moderator', 'پشتیبان'), ('user', 'کاربر'), ('counselor', 'خدمت دهنده'), ('guest', 'مهمان'), ('banned', 'مسدود')], default='user', max_length=20),
        ),
    ]
