# Generated by Django 6.0.7 on 2026-09-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_usersubscription_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='price_six_months',
            field=models.PositiveIntegerField(blank=True, help_text='خالی بگذارید تا این گزینه نمایش داده نشود', null=True, verbose_name='قیمت ۶ ماهه (تومان)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='price_yearly',
            field=models.PositiveIntegerField(blank=True, help_text='خالی بگذارید تا این گزینه نمایش داده نشود', null=True, verbose_name='قیمت سالانه (تومان)'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='billing_period',
            field=models.CharField(choices=[('monthly', 'ماهانه'), ('six_months', '۶ ماهه'), ('yearly', 'سالانه')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.PositiveIntegerField(verbose_name='قیمت ماهانه (تومان)'),
        ),
    ]
