# Generated by Django 6.0.7 on 2026-09-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='user_avatars/avatar.svg', null=True, upload_to='user_avatars/', verbose_name='عکس پروفایل'),
        ),
    ]
