# Generated by Django 6.0.7 on 2026-09-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_plan_price_six_months_plan_price_yearly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselor',
            name='plan',
            field=models.CharField(choices=[('bronze', 'برنزی'), ('silver', 'نقره\u200cای'), ('gold', 'طلایی'), ('company', 'سازمانی')], default='bronze', max_length=20),
        ),
        migrations.AddField(
            model_name='counselor',
            name='plan_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='tier',
            field=models.CharField(choices=[('bronze', 'برنزی'), ('silver', 'نقره\u200cای'), ('gold', 'طلایی'), ('company', 'سازمانی')], default='bronze', max_length=20),
        ),
    ]
