# Generated by Django 6.0.7 on 2026-09-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_counselor_plan_counselor_plan_expires_at_plan_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselor',
            name='is_purged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='counselor',
            name='purged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_free',
            field=models.BooleanField(default=False, help_text='در صورت فعال بودن، این پلن بدون نیاز به پرداخت فعال می\u200cشود', verbose_name='رایگان'),
        ),
    ]
